const rubrics = {
  posts: [
    {
      id: 100,
      title: "Бухгалтерия",
      url: "/rubricator/buhgalterija/",
      children: [
        {
          id: 5,
          title: "Бухгалтерский учет",
          url: "/rubricator/buhgalterskij-uchet/",
          count: 23,
        },
        {
          id: 10,
          title: "ВЭД",
          url: "/rubricator/ved/",
          count: 6,
        },
        {
          id: 16,
          title: "Первичка",
          url: "/rubricator/pervichnye-dokumenty/",
          count: 1,
        },
        {
          id: 19,
          title: "Аудит",
          url: "/rubricator/audit/",
          count: 3,
        },
        {
          id: 25,
          title: "Основные средства",
          url: "/rubricator/osnovnye-sredstva/",
          count: 1,
        },
        {
          id: 31,
          title: "Онлайн-кассы",
          url: "/rubricator/onlajn-kassy/",
          count: 7,
        },
        {
          id: 37,
          title: "Обособленные подразделения, филиалы",
          url: "/rubricator/obosoblennye-podrazdelenija-filialy/",
          count: 1,
        },
        {
          id: 158,
          title: "МСФО",
          url: "/rubricator/msfo/",
          count: 6,
        },
        {
          id: 160,
          title: "Делопроизводство",
          url: "/rubricator/deloproizvodstvo/",
          count: 1,
        },
        {
          id: 263,
          title: "Обзоры для бухгалтера",
          url: "/rubricator/obzory-dlya-buhgaltera/",
          count: 1,
        },
        {
          id: 312,
          title: "Блокировка счетов 115-ФЗ",
          url: "/rubricator/312/",
          count: 1,
        },
        {
          id: 318,
          title: "Расчеты с работниками",
          url: "/rubricator/rascheti/",
          count: 13,
        },
        {
          id: 449,
          title: "Дебиторская задолженность",
          url: "/rubricator/449/",
          count: 1,
        },
        {
          id: 450,
          title: "Бухгалтерский аутсорсинг",
          url: "/rubricator/450/",
          count: 2,
        },
        {
          id: 471,
          title: "Управленческий учет",
          url: "/rubricator/upravlencheskiy-uchet/",
          count: 6,
        },
      ],
      count: 90,
    },
    {
      id: 101,
      title: "Банки",
      url: "/rubricator/banki/",
      children: [
        {
          id: 72,
          title: "Кредиты",
          url: "/rubricator/kredity/",
          count: 2,
        },
        {
          id: 93,
          title: "Валютные операции",
          url: "/rubricator/valjutnye-operatsii/",
          count: 8,
        },
        {
          id: 228,
          title: "Электронные деньги",
          url: "/rubricator/elektronnye-dengi-raschety-elektronnymi-dengami/",
          count: 1,
        },
        {
          id: 446,
          title: "Наличные деньги",
          url: "/rubricator/446/",
          count: 1,
        },
      ],
      count: 1,
    },
    {
      id: 102,
      title: "Автоматизация учета",
      url: "/rubricator/avtomatizatsija-ucheta/",
      children: [
        {
          id: 43,
          title: "1С",
          url: "/rubricator/1c/",
          count: 4,
        },
        {
          id: 230,
          title: "ЭДО",
          url: "/rubricator/elektronnyj-dokumentooborot-elektronnaja-otchetnost/",
          count: 2,
        },
        {
          id: 275,
          title: "Электронная отчетность",
          url: "/rubricator/elektronnaja-otchetnost/",
          count: 1,
        },
      ],
      count: 1,
    },
    {
      id: 103,
      title: "Право",
      url: "/rubricator/pravo/",
      children: [
        {
          id: 15,
          title: "УК РФ",
          url: "/rubricator/uk-rf/",
          count: 3,
        },
        {
          id: 130,
          title: "ГК РФ",
          url: "/rubricator/gk-rf/",
          count: 1,
        },
        {
          id: 155,
          title: "Полиция",
          url: "/rubricator/policiya/",
          count: 4,
        },
        {
          id: 212,
          title: "Банкротство",
          url: "/rubricator/bankrotstvo/",
          count: 5,
        },
        {
          id: 225,
          title: "Госзакупки",
          url: "/rubricator/goszakupki/",
          count: 2,
        },
        {
          id: 262,
          title: "Антимонопольное право",
          url: "/rubricator/antimonopolnoe-pravo/",
          count: 1,
        },
        {
          id: 287,
          title: "Защита персональных данных",
          url: "/rubricator/zashita-personalnih-dannih/",
          count: 3,
        },
        {
          id: 438,
          title: "Субсидиарная ответственность",
          url: "/rubricator/438/",
          count: 4,
        },
        {
          id: 475,
          title: "Авторское право",
          url: "/rubricator/475/",
          count: 1,
        },
      ],
      count: 25,
    },
    {
      id: 105,
      title: "Налоги, взносы, пошлины",
      url: "/rubricator/nalogi-vznosy-poshlini/",
      children: [
        {
          id: 4,
          title: "НДС",
          url: "/rubricator/nds/",
          count: 16,
        },
        {
          id: 7,
          title: "Налог на имущество",
          url: "/rubricator/nalog-na-imuschestvo/",
          count: 3,
        },
        {
          id: 27,
          title: "НДФЛ",
          url: "/rubricator/ndfl/",
          count: 14,
        },
        {
          id: 30,
          title: "Транспортный налог",
          url: "/rubricator/transportnyj-nalog/",
          count: 2,
        },
        {
          id: 82,
          title: "Оптимизация налогообложения",
          url: "/rubricator/optimizatsija-nalogooblozhenija/",
          count: 25,
        },
        {
          id: 97,
          title: "Налоговые штрафы",
          url: "/rubricator/nalogovye-shtrafi/",
          count: 1,
        },
        {
          id: 213,
          title: "Страховые взносы",
          url: "/rubricator/strahovye-vznosy/",
          count: 12,
        },
        {
          id: 233,
          title: "Контролируемые сделки",
          url: "/rubricator/kontroliruemye-sdelki/",
          count: 2,
        },
        {
          id: 270,
          title: "Проверка контрагентов",
          url: "/rubricator/proverka-kontragentov/",
          count: 2,
        },
        {
          id: 445,
          title: "Налоговые изменения 2021",
          url: "/rubricator/445/",
          count: 8,
        },
      ],
      count: 9,
    },
    {
      id: 106,
      title: "Свой бизнес",
      url: "/rubricator/svoj-biznes/",
      children: [
        {
          id: 57,
          title: "Менеджмент",
          url: "/rubricator/menedzhment/",
          count: 2,
        },
        {
          id: 59,
          title: "Маркетинг",
          url: "/rubricator/marketing/",
          count: 1,
        },
        {
          id: 60,
          title: "Управление финансами",
          url: "/rubricator/upravlenie-finansami/",
          count: 3,
        },
        {
          id: 91,
          title: "Бизнес-психология",
          url: "/rubricator/biznes-psihologija/",
          count: 13,
        },
        {
          id: 329,
          title: "Индивидуальный предприниматель",
          url: "/rubricator/individualniy-predprinimatel/",
          count: 3,
        },
      ],
      count: 3,
    },
    {
      id: 126,
      title: "Отраслевой учет",
      url: "/rubricator/otraslevoj-uchet-i-spetsrezhimy/",
      children: [
        {
          id: 67,
          title: "Учет в строительстве",
          url: "/rubricator/uchet-v-stroitelstve/",
          count: 2,
        },
        {
          id: 112,
          title: "Учет в некоммерческих организациях",
          url: "/rubricator/uchet-v-nekommercheskih-organizatsijah/",
          count: 3,
        },
        {
          id: 284,
          title: "Маркировка товаров",
          url: "/rubricator/markirovka-tovarov/",
          count: 3,
        },
        {
          id: 476,
          title: "Прослеживаемость товаров",
          url: "/rubricator/476/",
          count: 2,
        },
      ],
      count: 0,
    },
    {
      id: 165,
      title: "Инвестиции",
      url: "/rubricator/investitsii/",
      children: [],
      count: 2,
    },
    {
      id: 290,
      title: "Интернет и IT",
      url: "/rubricator/internet/",
      children: [],
      count: 1,
    },
    {
      id: 295,
      title: "Отчетность",
      url: "/rubricator/otchetnost/",
      children: [
        {
          id: 239,
          title: "Бухгалтерская отчетность",
          url: "/rubricator/buhgalterskaja-otchetnost/",
          count: 2,
        },
        {
          id: 301,
          title: "Налоговая отчетность",
          url: "/rubricator/301/",
          count: 1,
        },
      ],
      count: 2,
    },
    {
      id: 296,
      title: "Проверки",
      url: "/rubricator/proverki/",
      children: [
        {
          id: 33,
          title: "Налоговые проверки",
          url: "/rubricator/nalogovye-proverki/",
          count: 37,
        },
        {
          id: 259,
          title: "Налоговый мониторинг",
          url: "/rubricator/nalogovyj-monitoring/",
          count: 1,
        },
      ],
      count: 7,
    },
    {
      id: 297,
      title: "Спецрежимы",
      url: "/rubricator/specrejimi/",
      children: [
        {
          id: 8,
          title: "ЕНВД",
          url: "/rubricator/envd/",
          count: 1,
        },
        {
          id: 29,
          title: "УСН",
          url: "/rubricator/usn/",
          count: 3,
        },
        {
          id: 235,
          title: "ПСН",
          url: "/rubricator/psn/",
          count: 2,
        },
        {
          id: 331,
          title: "Самозанятые",
          url: "/rubricator/samozanyatie/",
          count: 4,
        },
      ],
      count: 0,
    },
    {
      id: 299,
      title: "Кадры",
      url: "/rubricator/kadri/",
      children: [
        {
          id: 58,
          title: "Управление персоналом (аутсорсинг, аутстаффинг)",
          url: "/rubricator/upravlenie-personalom/",
          count: 2,
        },
        {
          id: 278,
          title: "Кадровый учет",
          url: "/rubricator/kadrovyj-uchet/",
          count: 9,
        },
        {
          id: 330,
          title: "Трудовые отношения",
          url: "/rubricator/trudovie-otnosheniya/",
          count: 10,
        },
        {
          id: 474,
          title: "Иностранные работники",
          url: "/rubricator/inostrannie-rabotniki/",
          count: 4,
        },
      ],
      count: 9,
    },
    {
      id: 313,
      title: "Бухгалтеры",
      url: "/rubricator/buhgalteri/",
      children: [
        {
          id: 314,
          title: "Психология для бухгалтера",
          url: "/rubricator/314/",
          count: 1,
        },
        {
          id: 315,
          title: "Карьера бухгалтера",
          url: "/rubricator/315/",
          count: 1,
        },
        {
          id: 316,
          title: "Обучение для бухгалтеров",
          url: "/rubricator/316/",
          count: 1,
        },
      ],
      count: 2,
    },
  ],
};

export default rubrics;
